services:
  - type: web
    name: ugforce-face
    runtime: docker
    dockerfilePath: python/Dockerfile
    dockerContext: python
    envVars:
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
    plan: free
    autoDeploy: true
